version: "3.9"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: "hw10django"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret01"
      PGDATA: "/var/lib/postgresq/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - hw10django-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  hw10django-data: